#!/usr/bin/python3
""" Storage for DBStorage to create new engine """

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, scoped_session
from models.base_model import BaseModel
from models.user import User
from models.state import State
from models.city import City
from models.amenity import Amenity
from models.place import Place
from models.review import Review
from os import getenv

Base = declarative_base()


class DBStorage:
    """Database storage engine using SQLALchemy"""
    __engine = None
    __session = None

    def __init__(self):
        """Initialization method"""
        self.__engine = create_engine('mysql+mysqldb://{}:{}@{}/{}'
                                      .format(getenv('HBNB_MYSQL_USER'),
                                              getenv('HBNB_MYSQL_PWD'),
                                              getenv('HBNB_MYSQL_HOST'),
                                              getenv('HBNB_MYSQL_DB')),
                                      echo=True,
                                      pool_pre_ping=True)

        if getenv('HBNB_ENV') == 'test':
            Base.metadata.drop_all(self.__engine)

    def all(self, cls=None):
        """Queries objects depending on the class name"""
        query_dict = {}
        classes = [City, State]
        if cls is None:
            for c in classes:
                objs = self.__session.query(c).all()
                for obj in objs:
                    key = '{}{}'.format(obj.__class__.__name__, obj.id)
                    query_dict[key] = obj
        else:
            objs = self.__session.query(cls).all()
            for obj in objs:
                key = '{}.{}'.format(obj.__class__.__name__, obj.id)
                query_dict[key] = obj
        return query_dict

    def new(self, obj):
        """Adds the object to the current database session"""
        self.__session.add(obj)

    def save(self):
        """Commits all changes to the current database session"""
        self.__session.commit()

    def delete(self, obj=None):
        """Deletes the object from the current database session"""
        if obj:
            self.__session.delete(obj)

    def reload(self):
        """creates all tbles in the database and creates a new session"""
        Base.metadata.create_all(self.__engine)
        session_factory = sessionmaker(
                           bind=self.__engine, expire_on_commit=False)
        Session = scoped_session(session_factory)
        self.__session = Session()
